/**
 *
 * Given the network data generated by scan-network.js, filters out servers that
 * cannot be hacked yet or do not produce money, scores the remainder, and
 * produces a sorted list of viable targets.
 * 
 */

import type { NS } from "@ns";
import { hasFormulas } from "/lib/ns/formulas.js";
import { computeXpScore } from "/lib/targets.js";
import { getTargetConfig } from "/domain/targets/config.js";

export interface NetworkInfo {
    hasAdminRights: boolean;
    moneyMax: number;
    requiredHackingSkill: number;
    minDifficulty: number;
    hackTime: number;
    weakenTime: number;
    growTime: number;
    numOpenPortsRequired: number;
}

export interface TargetInfo {
    host: string;
    score: number;
    xpScore: number;
    currentMoney: number;
    currentSecurity: number;
    minSecurity: number;
    maxMoney: number;
    requiredHackingSkill: number;
    hackTime: number;
    weakenTime: number;
    growTime: number;
}

export function scoreServers(ns: NS, network: Record<string, NetworkInfo>): TargetInfo[] {
    const hackingLevel = ns.getHackingLevel();
    const haveFormulas = hasFormulas(ns);
    const filters = getTargetConfig(ns).filters;
    const targets: TargetInfo[] = [];

    for (const host of Object.keys(network)) {
        const info = network[host];
        const currentMoney = ns.getServerMoneyAvailable(host);
        const currentSecurity = ns.getServerSecurityLevel(host);
        if (!info.hasAdminRights) continue;
        if (info.moneyMax <= filters.minAbsoluteMoney) continue;
        if (currentMoney <= info.moneyMax * filters.minRelativeMoney) continue;
        if (info.requiredHackingSkill > hackingLevel) continue;

        const server = ns.getServer(host);
        const player = ns.getPlayer();
        let score: number;
        if (haveFormulas) {    
            const fServer = { ...server, hackDifficulty: server.minDifficulty };
            const hackTime = ns.formulas.hacking.weakenTime(fServer, player);
            const hackChance = ns.formulas.hacking.hackChance(fServer, player);
            const hackPercent = ns.formulas.hacking.hackPercent(fServer, player);
            const expectedMoney = (server.moneyMax ?? 0) * hackPercent * hackChance;
            score = expectedMoney / (hackTime / 1000);
        } else {
            const cycleTime = info.hackTime + info.weakenTime + info.growTime;
            score = info.moneyMax / info.minDifficulty / (cycleTime / 1000);
        }

        const xpScore = computeXpScore(ns, server, player);

        targets.push({
            host,
            score,
            xpScore,
            currentMoney,
            currentSecurity,
            minSecurity: info.minDifficulty,
            maxMoney: info.moneyMax,
            requiredHackingSkill: info.requiredHackingSkill,
            hackTime: info.hackTime,
            weakenTime: info.weakenTime,
            growTime: info.growTime
        });
    }
    targets.sort((a, b) => b.score - a.score);
    return targets;
}
