/**
 * score-targets.js
 *
 * Reads the network data generated by scan-network.js, filters out servers that
 * cannot be hacked yet or do not produce money, scores the remainder, and
 * produces a sorted list of viable targets. The scoring is simple: the maximum
 * money a server holds divided by the hack time (in seconds) and weighted by
 * the required hacking level. A lower required hacking level and a higher
 * maximum money yields a better score.
 *
 * The resulting array is written to /data/targets.json. The top few targets
 * are also printed to the terminal for the player's convenience.
 *
 * Usage: run scripts/score-targets.js
 *
 * Dependencies: lib/ns-io.js, lib/constants.js
 */

import {readJSON, writeJSON} from '/lib/ns-io.js';
import {NETWORK_FILE, TARGETS_FILE, MIN_ABSOLUTE_MONEY, MIN_RELATIVE_MONEY} from '/lib/constants.js';
import {formatMoney, formatTime} from '/lib/util.js';

/** @param {NS} ns */
export async function main(ns) {
  const network = await readJSON(ns, NETWORK_FILE) || {};
  const hackingLevel = ns.getHackingLevel();
  const targets = [];

  for (const host of Object.keys(network)) {
    const info = network[host];
    const currentMoney = ns.getServerMoneyAvailable(host);
    if (!info.hasAdminRights) continue;
    if (info.moneyMax <= MIN_ABSOLUTE_MONEY) continue;
    if (currentMoney <= info.moneyMax * MIN_RELATIVE_MONEY) continue;
    if (info.requiredHackingSkill > hackingLevel) continue;

    const cycleTime = info.hackTime + info.weakenTime + info.growTime;
    const score = info.moneyMax / info.minDifficulty / cycleTime;

    targets.push({
      host,
      score,
      currentMoney,
      maxMoney: info.moneyMax,
      reqHack: info.requiredHackingSkill,
      hackTime: info.hackTime,
      weakenTime: info.weakenTime,
      growTime: info.growTime
    });
  }

  targets.sort((a, b) => b.score - a.score);
  await writeJSON(ns, TARGETS_FILE, targets);

  // Display the top five targets in a human-readable format
  if (targets.length === 0) {
    ns.tprint('score-targets: no hackable servers found');
    return;
  }
  
  const topTargets =
    'Top targets:\n' +
    targets.slice(0, 5).map(renderTarget).join('\n');
  ns.tprint(topTargets);
}

function renderTarget(t, i) {
  return `${i + 1}. ${t.host}
   score: $${formatMoney(t.score)} per security-point per millisecond
   money: $${formatMoney(t.currentMoney)} available of $${formatMoney(t.maxMoney)} 
   cycle: hack: ${formatTime(t.hackTime)}, weaken: ${formatTime(t.weakenTime)}, grow: ${formatTime(t.growTime)}
   required hacking level: ${t.reqHack}`;
}

