/**
* score-targets.js
*
* Reads the network data generated by scan-network.js, filters out servers that
* cannot be hacked yet or do not produce money, scores the remainder, and
* produces a sorted list of viable targets. 
*
* The resulting array is written to /data/targets.json. The top few targets
* are also printed to the terminal for the player's convenience.
*
* Usage: run scripts/score-targets.js
*
* Dependencies: lib/ns-io.js, lib/constants.js
*/

import { readJSON, writeJSON } from '/lib/ns-io.js';
import { NETWORK_FILE, TARGETS_FILE, MIN_ABSOLUTE_MONEY, MIN_RELATIVE_MONEY } from '/lib/constants.js';
import { formatMoney, formatTime } from '/lib/util.js';
import { computeXpScore } from '/lib/targets.js';

/** @param {NS} ns */
export async function main(ns) {
    const network = await readJSON(ns, NETWORK_FILE) || {};
    const hackingLevel = ns.getHackingLevel();
    const haveFormulas = ns.fileExists("Formulas.exe", "home") && ns.formulas?.hacking;
    const targets = [];

    for (const host of Object.keys(network)) {
        const info = network[host];
        const currentMoney = ns.getServerMoneyAvailable(host);
        const currentSecurity = ns.getServerSecurityLevel(host);
        if (!info.hasAdminRights) continue;
        if (info.moneyMax <= MIN_ABSOLUTE_MONEY) continue;
        if (currentMoney <= info.moneyMax * MIN_RELATIVE_MONEY) continue;
        if (info.requiredHackingSkill > hackingLevel) continue;

        let score;
        if (haveFormulas) {
            const server = ns.getServer(host); // fresh snapshot
            const player = ns.getPlayer();
            const fServer = { ...server, hackDifficulty: server.minDifficulty };
            const hackTime = ns.formulas.hacking.weakenTime(fServer, player);
            const hackChance = ns.formulas.hacking.hackChance(fServer, player);
            const hackPercent = ns.formulas.hacking.hackPercent(fServer, player);
            const expectedMoney = server.moneyMax * hackPercent * hackChance;
            score = expectedMoney / (hackTime / 1000);
        }
        else {
            const cycleTime = info.hackTime + info.weakenTime + info.growTime;
            score = info.moneyMax / info.minDifficulty / (cycleTime / 1000);
        }

        const xpScore = computeXpScore(ns, info, ns.getPlayer());

        targets.push({
            host,
            score,
            xpScore,
            currentMoney,
            currentSecurity,
            minSecurity: info.minDifficulty,
            maxMoney: info.moneyMax,
            requiredHackingSkill: info.requiredHackingSkill,
            hackTime: info.hackTime,
            weakenTime: info.weakenTime,
            growTime: info.growTime
        });
    }

    targets.sort((a, b) => b.score - a.score);
    await writeJSON(ns, TARGETS_FILE, targets);

    // Display the top five targets in a human-readable format
    if (targets.length === 0) {
        ns.tprint('score-targets: no hackable servers found');
        return;
    }

    function renderTarget(t, i) {
        return `${i + 1}. ${t.host}
   score: $${formatMoney(t.score)} ${haveFormulas ? 'per second' : 'per security-point per second (max)'}
   money: $${formatMoney(t.currentMoney)} available of $${formatMoney(t.maxMoney)} 
   cycle: hack: ${formatTime(t.hackTime)}, weaken: ${formatTime(t.weakenTime)}, grow: ${formatTime(t.growTime)}
   security: required: ${t.requiredHackingSkill}, min: ${t.minSecurity}, current: ${t.currentSecurity.toFixed(2)}`;
    }

    const topTargets =
        `Player hacking level ${hackingLevel} Formulas unlocked: ${haveFormulas ? "yes" : "no"}\nTop targets:\n` +
        targets.slice(0, 4).map(renderTarget).join('\n');
    ns.tprint(topTargets);
}


