/**
 *
 * Reads the network data generated by scan-network.js, filters out servers that
 * cannot be hacked yet or do not produce money, scores the remainder, and
 * produces a sorted list of viable targets.
 *
 * The resulting array is written to /data/targets.json. The top few targets
 * are also printed to the terminal for the player's convenience.
 *
 * Usage: run scripts/score-targets.js
 *
 * Dependencies: lib/ns-io.js, lib/constants.js
 */

import type { NS } from "@ns";
import { hasFormulas } from "/lib/ns/formulas.js";
import { readJSON, writeJSON } from "/lib/ns/io.js";
import { formatMoney, formatTime } from "/lib/util.js";
import { scoreServers } from "/domain/targets/scoring.js";
import type { NetworkInfo, TargetInfo } from "/domain/targets/scoring.js";
import { getTargetConfig } from "/domain/targets/config.js";


export async function main(ns: NS): Promise<void> {
    const targetCfg = getTargetConfig(ns);
    const networkFile = targetCfg.networkFile;
    const targetsFile = targetCfg.targetsFile;

    const network: Record<string, NetworkInfo> = (await readJSON(ns, networkFile) || {}) as Record<string, NetworkInfo>;
    const targets: TargetInfo[] = scoreServers(ns, network);
    writeJSON(ns, targetsFile, targets);

    // Display the top five targets in a human-readable format
    if (targets.length === 0) {
        //ns.tprint("score-targets: no hackable servers found");
        return;
    }

    const haveFormulas = hasFormulas(ns);
    const hackingLevel = ns.getHackingLevel();

    function renderTarget(t: TargetInfo, i: number): string {
        return `${i + 1}. ${t.host}
   score: $${formatMoney(t.score)} ${haveFormulas ? "per second" : "per security-point per second (max)"}
   money: $${formatMoney(t.currentMoney)} available of $${formatMoney(t.maxMoney)} 
   cycle: hack: ${formatTime(t.hackTime)}, weaken: ${formatTime(t.weakenTime)}, grow: ${formatTime(t.growTime)}
   security: required: ${t.requiredHackingSkill}, min: ${t.minSecurity}, current: ${t.currentSecurity.toFixed(2)}`;
    }

    const topTargets =
        `Player hacking level ${hackingLevel} Formulas unlocked: ${haveFormulas ? "yes" : "no"}\nTop targets:\n` +
        targets.slice(0, 4).map(renderTarget).join("\n");
    //ns.tprint(topTargets);
}
