/**
 * score-targets.js
 *
 * Reads the network data generated by scan-network.js, filters out servers that
 * cannot be hacked yet or do not produce money, scores the remainder, and
 * produces a sorted list of viable targets. The scoring is simple: the maximum
 * money a server holds divided by the hack time (in seconds) and weighted by
 * the required hacking level. A lower required hacking level and a higher
 * maximum money yields a better score.
 *
 * The resulting array is written to /data/targets.json. The top few targets
 * are also printed to the terminal for the player's convenience.
 *
 * Usage: run scripts/score-targets.js
 *
 * Dependencies: lib/ns-io.js, lib/constants.js
 */

import {readJSON, writeJSON} from '/lib/ns-io.js';
import {NETWORK_FILE, TARGETS_FILE, MIN_ABSOLUTE_MONEY, MIN_RELATIVE_MONEY} from '/lib/constants.js';

/** @param {NS} ns */
export async function main(ns) {
  const network = await readJSON(ns, NETWORK_FILE) || {};
  const hackingLevel = ns.getHackingLevel();
  const targets = [];

  for (const host of Object.keys(network)) {
    const info = network[host];
    const currentMoney = ns.getServerMoneyAvailable(host);
    if (!info.hasAdminRights) continue;
    if (info.moneyMax <= MIN_ABSOLUTE_MONEY) continue;
    if (currentMoney <= info.moneyMax * MIN_RELATIVE_MONEY) continue;
    if (info.requiredHackingSkill > hackingLevel) continue;

    const hackTime = ns.getHackTime(host); // milliseconds
    // Score formula: maximize money while minimizing hack time and required hack level.
    const score = info.moneyMax / ((hackTime / 1000) * (info.requiredHackingSkill + 1));
    targets.push({
      host,
      score,
      currentMoney,
      maxMoney: info.moneyMax,
      reqHack: info.requiredHackingSkill,
      hackTime
    });
  }

  targets.sort((a, b) => b.score - a.score);
  await writeJSON(ns, TARGETS_FILE, targets);

  // Display the top five targets in a human-readable format
  if (targets.length === 0) {
    ns.tprint('score-targets: no hackable servers found');
    return;
  }
  ns.tprint('Top targets:');
  for (let i = 0; i < Math.min(5, targets.length); i++) {
    const t = targets[i];
    ns.tprint(`${i + 1}. ${t.host} | score: ${t.score.toFixed(2)} | current: $${ns.formatNumber(t.currentMoney, 2)} | max: $${ns.formatNumber(t.maxMoney, 2)} | reqHack: ${t.reqHack}`);
  }
}